/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Functions.Accounts;
import Functions.SearchingFunctions;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import static java.lang.System.in;
import java.nio.file.Files;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ziad asem
 */

public class Home extends javax.swing.JFrame {
    DefaultListModel model ;    // Any list changing in runtime --> Model.
    DefaultListModel model2 ;
    Accounts accounts;
    Scanner sc;
    SearchingFunctions srch;
    public Home(Accounts _accounts) {
        
        model = new DefaultListModel();
        model2 = new DefaultListModel();
        
       initComponents();
       jList2.setModel(model2);
       update.setVisible(false);
       
       
       this.setLocationRelativeTo(null);
       
        accounts = _accounts ;
        try {
            sc = new Scanner(new File(_accounts.getUserName() + ".txt"),  "UTF-8");
            srch = new SearchingFunctions(sc);
        } catch (FileNotFoundException ex) {
            System.out.println("not found");
            //TODO HANDLE THIS EXCEPTION
        }
        
                Name.setText("Welcome ... " + accounts.getName());
                Name1.setText("Welcome ... " + accounts.getName());
                Name2.setText("Welcome ... " + accounts.getName());
                
                for (int i = 3 ; i < srch.getEntriesLength() ; i++){
                 String asem = srch.getEntries()[i];
                StringTokenizer token = new StringTokenizer(asem ,"|");
               
              model.add(i-3 ,token.nextToken() + " || " + token.nextToken());  
                }

               jLabel11.setText("Total number of words: "+(srch.getEntriesLength()-3));
               
          this.addWindowListener(new WindowAdapter() {
           @Override
           
            public void windowClosing(WindowEvent e) {

            // System.exit(0);
            srch.updateFile();

}

  });
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        Res = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EnglishKey = new javax.swing.JTextField();
        EngAr = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ArEng = new javax.swing.JButton();
        ArabKey = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jEdit = new java.awt.Button();
        jLogout = new java.awt.Button();
        DarkMode = new java.awt.Button();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        AddAr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddEng = new javax.swing.JTextField();
        Adder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Name1 = new javax.swing.JLabel();
        jEdit1 = new java.awt.Button();
        jLogout1 = new java.awt.Button();
        DarkMode1 = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        jEdit2 = new java.awt.Button();
        jLogout2 = new java.awt.Button();
        DarkMode2 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Single = new javax.swing.JRadioButton();
        Multiple = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        FilterWords = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        charFilter = new javax.swing.JTextField();
        update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Dictionary");
        setMinimumSize(new java.awt.Dimension(1150, 750));
        setSize(new java.awt.Dimension(850, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel1.setRequestFocusEnabled(false);

        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(850, 500));

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 153, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel2.setBackground(new java.awt.Color(222, 222, 222));
        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Translation");

        Res.setEditable(false);
        Res.setBackground(new java.awt.Color(235, 235, 235));
        Res.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Res.setForeground(new java.awt.Color(0, 0, 0));
        Res.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("English");
        jLabel5.setPreferredSize(new java.awt.Dimension(106, 43));

        EnglishKey.setBackground(new java.awt.Color(235, 235, 235));
        EnglishKey.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        EnglishKey.setForeground(new java.awt.Color(0, 0, 0));
        EnglishKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnglishKey.setPreferredSize(new java.awt.Dimension(250, 85));
        EnglishKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishKeyActionPerformed(evt);
            }
        });

        EngAr.setBackground(new java.awt.Color(51, 168, 249));
        EngAr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        EngAr.setForeground(new java.awt.Color(51, 51, 51));
        EngAr.setText("Translate");
        EngAr.setToolTipText("Translate English Word into Arabic");
        EngAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngArActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(222, 222, 222));
        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Arabic");
        jLabel6.setMaximumSize(new java.awt.Dimension(106, 43));

        ArEng.setBackground(new java.awt.Color(51, 153, 255));
        ArEng.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ArEng.setForeground(new java.awt.Color(51, 51, 51));
        ArEng.setText("Translate");
        ArEng.setToolTipText("Translate Arabic word into English");
        ArEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArEngActionPerformed(evt);
            }
        });

        ArabKey.setBackground(new java.awt.Color(235, 235, 235));
        ArabKey.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ArabKey.setForeground(new java.awt.Color(0, 0, 0));
        ArabKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArabKey.setPreferredSize(new java.awt.Dimension(250, 85));
        ArabKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArabKeyActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(204, 204, 204), null, null)));
        jPanel2.setOpaque(false);

        Name.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 0, 0));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name.setText("Name");

        jEdit.setActionCommand("jEdit");
        jEdit.setBackground(new java.awt.Color(153, 153, 153));
        jEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jEdit.setForeground(new java.awt.Color(255, 255, 255));
        jEdit.setLabel("Edit User");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jLogout.setActionCommand("jLogout");
        jLogout.setBackground(new java.awt.Color(153, 153, 153));
        jLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setLabel("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        DarkMode.setActionCommand("jEdit");
        DarkMode.setBackground(new java.awt.Color(153, 153, 153));
        DarkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DarkMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DarkMode.setForeground(new java.awt.Color(255, 255, 255));
        DarkMode.setLabel("Mode");
        DarkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DarkModeMouseEntered(evt);
            }
        });
        DarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        Name.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EngAr, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnglishKey, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ArabKey, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArEng, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArabKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnglishKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EngAr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArEng, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Translate", kGradientPanel1);

        kGradientPanel2.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkStartColor(new java.awt.Color(51, 153, 255));

        AddAr.setBackground(new java.awt.Color(235, 235, 235));
        AddAr.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        AddAr.setForeground(new java.awt.Color(0, 0, 0));
        AddAr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddAr.setPreferredSize(new java.awt.Dimension(250, 85));
        AddAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddArActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(222, 222, 222));
        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Arabic");

        jLabel1.setBackground(new java.awt.Color(222, 222, 222));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("English");

        AddEng.setBackground(new java.awt.Color(235, 235, 235));
        AddEng.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        AddEng.setForeground(new java.awt.Color(0, 0, 0));
        AddEng.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddEng.setPreferredSize(new java.awt.Dimension(250, 85));
        AddEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEngActionPerformed(evt);
            }
        });

        Adder.setBackground(new java.awt.Color(51, 168, 249));
        Adder.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Adder.setForeground(new java.awt.Color(51, 51, 51));
        Adder.setMnemonic('a');
        Adder.setText("Add Word");
        Adder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdderActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(204, 204, 204), null, null)));
        jPanel3.setOpaque(false);

        Name1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Name1.setForeground(new java.awt.Color(0, 0, 0));
        Name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name1.setText("Name");

        jEdit1.setActionCommand("jEdit");
        jEdit1.setBackground(new java.awt.Color(153, 153, 153));
        jEdit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jEdit1.setForeground(new java.awt.Color(255, 255, 255));
        jEdit1.setLabel("Edit User");
        jEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdit1ActionPerformed(evt);
            }
        });

        jLogout1.setActionCommand("jLogout");
        jLogout1.setBackground(new java.awt.Color(153, 153, 153));
        jLogout1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLogout1.setForeground(new java.awt.Color(255, 255, 255));
        jLogout1.setLabel("Logout");
        jLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogout1ActionPerformed(evt);
            }
        });

        DarkMode1.setActionCommand("jEdit");
        DarkMode1.setBackground(new java.awt.Color(153, 153, 153));
        DarkMode1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DarkMode1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DarkMode1.setForeground(new java.awt.Color(255, 255, 255));
        DarkMode1.setLabel("Mode");
        DarkMode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DarkMode1MouseEntered(evt);
            }
        });
        DarkMode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkMode1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarkMode1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DarkMode1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total number of words:");
        jLabel11.setAlignmentX(0.5F);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AddEng, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(AddAr, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Adder, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(Adder, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(93, 93, 93)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Word", kGradientPanel2);

        kGradientPanel3.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel3.setkGradientFocus(200);
        kGradientPanel3.setkStartColor(new java.awt.Color(51, 153, 255));
        kGradientPanel3.setkTransparentControls(false);

        jLabel4.setBackground(new java.awt.Color(222, 222, 222));
        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contents");

        jList1.setBackground(new java.awt.Color(207, 232, 243));
        jList1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jList1.setModel(model);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setPreferredSize(null);
        jScrollPane1.setViewportView(jList1);

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(204, 204, 204), null, null)));
        jPanel4.setOpaque(false);

        Name2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Name2.setForeground(new java.awt.Color(0, 0, 0));
        Name2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name2.setText("Name");

        jEdit2.setActionCommand("jEdit");
        jEdit2.setBackground(new java.awt.Color(153, 153, 153));
        jEdit2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jEdit2.setForeground(new java.awt.Color(255, 255, 255));
        jEdit2.setLabel("Edit User");
        jEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdit2ActionPerformed(evt);
            }
        });

        jLogout2.setActionCommand("jLogout");
        jLogout2.setBackground(new java.awt.Color(153, 153, 153));
        jLogout2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLogout2.setForeground(new java.awt.Color(255, 255, 255));
        jLogout2.setLabel("Logout");
        jLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogout2ActionPerformed(evt);
            }
        });

        DarkMode2.setActionCommand("jEdit");
        DarkMode2.setBackground(new java.awt.Color(153, 153, 153));
        DarkMode2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DarkMode2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DarkMode2.setForeground(new java.awt.Color(255, 255, 255));
        DarkMode2.setLabel("Mode");
        DarkMode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DarkMode2MouseEntered(evt);
            }
        });
        DarkMode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkMode2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarkMode2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DarkMode2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jList2.setBackground(new java.awt.Color(207, 232, 243));
        jList2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jList2.setModel(model2);
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray))));
        jPanel6.setToolTipText("Choose a word(s) from the content list to delete");
        jPanel6.setOpaque(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 255), java.awt.Color.darkGray));
        jPanel5.setOpaque(false);

        Delete.setBackground(new java.awt.Color(51, 168, 249));
        Delete.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Delete.setForeground(new java.awt.Color(51, 51, 51));
        Delete.setText("Delete");
        Delete.setToolTipText("Choose a word(s) from the content list to delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jPanel7.setToolTipText("Content words selection (Single mode / Multiple Mode)"); // NOI18N
        jPanel7.setOpaque(false);

        Single.setBackground(new java.awt.Color(255, 255, 255));
        DeleteMode.add(Single);
        Single.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Single.setForeground(new java.awt.Color(255, 255, 255));
        Single.setText("Single Word");
        Single.setToolTipText("Content words selection (Single mode)");
        Single.setOpaque(false);
        Single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleActionPerformed(evt);
            }
        });

        Multiple.setBackground(new java.awt.Color(255, 255, 255));
        DeleteMode.add(Multiple);
        Multiple.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Multiple.setForeground(new java.awt.Color(255, 255, 255));
        Multiple.setText("Multiple Words");
        Multiple.setToolTipText("Content words selection (Multiple Mode)");
        Multiple.setOpaque(false);
        Multiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultipleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Single, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Multiple, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Single, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Multiple)
                .addContainerGap())
        );

        jLabel7.setBackground(new java.awt.Color(222, 222, 222));
        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mode Selection");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jLabel8.setBackground(new java.awt.Color(222, 222, 222));
        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Delete Words");
        jLabel8.setToolTipText("Delete a word(s) from the content");

        Edit.setBackground(new java.awt.Color(51, 168, 249));
        Edit.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Edit.setForeground(new java.awt.Color(51, 51, 51));
        Edit.setText("Edit");
        Edit.setToolTipText("Edit a word from content ");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(222, 222, 222));
        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edit Word");
        jLabel9.setToolTipText("Edit a word from content ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(Edit)
                .addGap(42, 42, 42))
        );

        FilterWords.setBackground(new java.awt.Color(222, 222, 222));
        FilterWords.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        FilterWords.setForeground(new java.awt.Color(51, 51, 51));
        FilterWords.setText("Filter");

        jPanel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray))));
        jPanel8.setToolTipText("Filter words by character");
        jPanel8.setOpaque(false);

        jButton3.setBackground(new java.awt.Color(51, 168, 249));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Filter");
        jButton3.setToolTipText("Filter words by character");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(222, 222, 222));
        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Character");
        jLabel10.setToolTipText("Filter words by character");

        charFilter.setBackground(new java.awt.Color(235, 235, 235));
        charFilter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        charFilter.setForeground(new java.awt.Color(0, 0, 0));
        charFilter.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(charFilter))
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(charFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        update.setBackground(new java.awt.Color(222, 222, 222));
        update.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update.setText("Word Update");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FilterWords)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(FilterWords, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View contents", kGradientPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdderActionPerformed
        if((AddEng.getText().compareTo("")==0||AddEng.getText().compareTo(" ")==0)||(AddAr.getText().compareTo("")==0||AddAr.getText().compareTo(" ")==0))
        {
            JOptionPane.showMessageDialog(this, "Please enter a valid word", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }
        else{
        if (!AddEng.getText().isBlank() && !AddAr.getText().isBlank()){
            System.out.println(AddEng.getText());
            srch.addSorted(AddEng.getText(), AddAr.getText(), accounts.getUserName());
            model.clear();
            for (int i = 3 ; i < srch.getEntriesLength() ; i++){
                String asem = srch.getEntries()[i];
                System.out.println(asem);
                model.add(i-3,asem );
            }
            AddEng.setText("");
            AddAr.setText("");
        }
        }
        jLabel11.setText("Total number of words: "+(srch.getEntriesLength()-3));
    }//GEN-LAST:event_AdderActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        srch.updateFile();
        accounts.logout();
        this.dispose();
        new SignInScreen().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        this.dispose();
        new AccountEdit(accounts).setVisible(true);
    }//GEN-LAST:event_jEditActionPerformed

    private void ArabKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArabKeyActionPerformed

    }//GEN-LAST:event_ArabKeyActionPerformed

    private void ArEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArEngActionPerformed

        /*Scanner sc = new Scanner(new File("Dummy.txt"),  "UTF-8");

        SearchingFunctions srch = new SearchingFunctions(sc);*/
        if(Res.getText().compareTo(" ")==0){
            JOptionPane.showMessageDialog(this,"Word was not found","Invalid Word",JOptionPane.WARNING_MESSAGE);
        }
        else{
        if(ArabKey.getText().compareTo(" ")==0||ArabKey.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter a valid word", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }
        else{
        String engRes = srch.searchArab(ArabKey.getText());
        Res.setText(engRes);
        }
        }
        //arRes.setText(arKeying);
        // }
    }//GEN-LAST:event_ArEngActionPerformed

    private void EngArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngArActionPerformed
        /*  try {
            Scanner sc = new Scanner(new File("Dummy.txt"),  "UTF-8");

            SearchingFunctions srch = new SearchingFunctions(sc);*/
        if(Res.getText().compareTo(" ")==0){
            JOptionPane.showMessageDialog(this,"Word was not found","Invalid Word",JOptionPane.WARNING_MESSAGE);
        }
        else{
        if(EnglishKey.getText().compareTo(" ")==0||EnglishKey.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter a valid word", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String arRes = srch.searchEng(EnglishKey.getText());
            Res.setText(arRes);
        }
        }
            //arRes.setText(arKeying);
            /* } catch (FileNotFoundException ex) {
            System.out.println("Not found file");
        }*/
    }//GEN-LAST:event_EngArActionPerformed

    private void ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResActionPerformed

    private void jEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdit1ActionPerformed
        this.dispose();
        new AccountEdit(accounts).setVisible(true);
    }//GEN-LAST:event_jEdit1ActionPerformed

    private void jLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogout1ActionPerformed
        srch.updateFile();
        accounts.logout();
        this.dispose();
        new SignInScreen().setVisible(true);
    }//GEN-LAST:event_jLogout1ActionPerformed

    private void jEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdit2ActionPerformed
        this.dispose();
        new AccountEdit(accounts).setVisible(true);
    }//GEN-LAST:event_jEdit2ActionPerformed

    private void jLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogout2ActionPerformed
         srch.updateFile();
        accounts.logout();
        this.dispose();
        new SignInScreen().setVisible(true);
    }//GEN-LAST:event_jLogout2ActionPerformed

    
    
    
    private void MultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultipleActionPerformed
        jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_MultipleActionPerformed

    private void SingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleActionPerformed
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_SingleActionPerformed

    private void AddArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddArActionPerformed
        
    }//GEN-LAST:event_AddArActionPerformed

    private void EnglishKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishKeyActionPerformed

    private void AddEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEngActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
    if(Single.isSelected())
        {
        srch.deleteWord(jList1.getSelectedIndex());
         updateList();
         update.setText("Word Successfully Deleted ...");
         update.setVisible(true);
        }
        else if(Multiple.isSelected())
            {
                    for(int i= 0; i< jList1.getSelectedIndices().length; i++)
                    {
                        srch.deleteWord(jList1.getSelectedIndices()[i]-i);
                    }
                    updateList();
                    update.setText("Words Successfully Deleted ...");
                    update.setVisible(true);
            }
        else{
                JOptionPane.showMessageDialog(this, "Choose Mode First !!!", "Error", JOptionPane.WARNING_MESSAGE);
            }
            jLabel11.setText("Total number of words: "+(srch.getEntriesLength()-3));

    }//GEN-LAST:event_DeleteActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       try{
        if(jList1.getSelectedIndex() != -1)
        {
        String engWord = " ";  
        engWord = JOptionPane.showInputDialog(this, "Choose The New English Word", "Edit English", JOptionPane.INFORMATION_MESSAGE);
        String araWord = " ";
        
        if(engWord.compareTo("")==0){
            JOptionPane.showMessageDialog(this,"You didn't enter a word","Empty Field",JOptionPane.WARNING_MESSAGE);
        }
        else{
        araWord = JOptionPane.showInputDialog(this, "Choose The New Arabic Word", "Edit Arabic", JOptionPane.INFORMATION_MESSAGE);
        if(araWord.compareTo("")==0){
            JOptionPane.showMessageDialog(this,"You didn't enter a word","Empty Field",JOptionPane.WARNING_MESSAGE);
        }
        else{
        srch.deleteWord(jList1.getSelectedIndex());
        srch.addSorted(engWord, araWord, accounts.getUserName());
        updateList();
        update.setText("Word Successfully Edited ...");
        update.setVisible(true);
            }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Choose the word First !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }
        }
        
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Word wasn't edited", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_EditActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(charFilter.getText().equals(""))
                JOptionPane.showMessageDialog(this, "You didn't write a character", "Choose character", JOptionPane.WARNING_MESSAGE);
        else if(srch.empty_filterList(charFilter.getText().charAt(0)))
        {
            JOptionPane.showMessageDialog(this, "The character you chose is inappropiate or doesn't exist.", "Character Error", JOptionPane.ERROR_MESSAGE);
        }

        else
            {
                DefaultListModel<String> model3 = srch.filterList(charFilter.getText().charAt(0));
                model2.clear();
                for (int i = 0 ; i <model3.getSize() ; i++){
                     model2.add(i, model3.get(i));
                }
            }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkModeActionPerformed
        if(accounts.dark == false)
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel1.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(237,237,237));
            jLabel6.setForeground(new java.awt.Color(237,237,237));
            jLabel2.setForeground(new java.awt.Color(237,237,237));
            EngAr.setForeground(new java.awt.Color(237,237,237));
            EngAr.setBackground(new java.awt.Color(7,131,216));
            ArEng.setForeground(new java.awt.Color(237,237,237));
            ArEng.setBackground(new java.awt.Color(7,131,216));
            Name.setForeground(Color.white);
            ArabKey.setBackground(new java.awt.Color(222,222,222));
            EnglishKey.setBackground(new java.awt.Color(222,222,222));
            Res.setBackground(new java.awt.Color(222,222,222));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel2.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(237,237,237));
            jLabel3.setForeground(new java.awt.Color(237,237,237));
            jLabel11.setForeground(new java.awt.Color(237,237,237));
            Adder.setForeground(new java.awt.Color(237,237,237));
            Adder.setBackground(new java.awt.Color(7,131,216));
            Name1.setForeground(Color.white);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel3.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(237,237,237));
            FilterWords.setForeground(new java.awt.Color(237,237,237));
            update.setForeground(new java.awt.Color(237,237,237));
            jLabel10.setForeground(new java.awt.Color(237,237,237));
            jLabel9.setForeground(new java.awt.Color(237,237,237));
            jLabel8.setForeground(new java.awt.Color(237,237,237));
            jLabel7.setForeground(new java.awt.Color(237,237,237));
            Delete.setForeground(new java.awt.Color(237,237,237));
            Delete.setBackground(new java.awt.Color(7,131,216));
            Edit.setForeground(new java.awt.Color(237,237,237));
            Edit.setBackground(new java.awt.Color(7,131,216));
            jButton3.setForeground(new java.awt.Color(237,237,237));
            jButton3.setBackground(new java.awt.Color(7,131,216));
            charFilter.setBackground(new java.awt.Color(222,222,222));
            Name2.setForeground(Color.white);
            jList1.setBackground(new java.awt.Color(178,194,201));
            jList2.setBackground(new java.awt.Color(178,194,201));
        }
        else
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel1.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(51, 51, 51));
            jLabel6.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setBackground(new java.awt.Color(51,168,249));
            ArEng.setForeground(new java.awt.Color(51, 51, 51));
            ArEng.setBackground(new java.awt.Color(51,168,249));
            Name.setForeground(Color.black);
            ArabKey.setBackground(new java.awt.Color(235,235,235));
            EnglishKey.setBackground(new java.awt.Color(235,235,235));
            Res.setBackground(new java.awt.Color(235,235,235));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel2.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(51, 51, 51));
            jLabel3.setForeground(new java.awt.Color(51, 51, 51));
            jLabel11.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setBackground(new java.awt.Color(51,168,249));
            Name1.setForeground(Color.black);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel3.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(51, 51, 51));
            FilterWords.setForeground(new java.awt.Color(51, 51, 51));
            update.setForeground(new java.awt.Color(51, 51, 51));
            jLabel10.setForeground(new java.awt.Color(51, 51, 51));
            jLabel9.setForeground(new java.awt.Color(51, 51, 51));
            jLabel8.setForeground(new java.awt.Color(51, 51, 51));
            jLabel7.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setBackground(new java.awt.Color(51,168,249));
            Edit.setForeground(new java.awt.Color(51, 51, 51));
            Edit.setBackground(new java.awt.Color(51,168,249));
            jButton3.setForeground(new java.awt.Color(51, 51, 51));
            jButton3.setBackground(new java.awt.Color(51,168,249));
            charFilter.setBackground(new java.awt.Color(235,235,235));
            Name2.setForeground(Color.black);
            jList1.setBackground(new java.awt.Color(207,232,243));
            jList2.setBackground(new java.awt.Color(207,232,243));
        }
    }//GEN-LAST:event_DarkModeActionPerformed

    private void DarkModeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarkModeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DarkModeMouseEntered

    private void DarkMode1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarkMode1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DarkMode1MouseEntered

    private void DarkMode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkMode1ActionPerformed
        if(accounts.dark == false)
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel1.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(237,237,237));
            jLabel6.setForeground(new java.awt.Color(237,237,237));
            jLabel2.setForeground(new java.awt.Color(237,237,237));
            EngAr.setForeground(new java.awt.Color(237,237,237));
            EngAr.setBackground(new java.awt.Color(7,131,216));
            ArEng.setForeground(new java.awt.Color(237,237,237));
            ArEng.setBackground(new java.awt.Color(7,131,216));
            Name.setForeground(Color.white);
            ArabKey.setBackground(new java.awt.Color(222,222,222));
            EnglishKey.setBackground(new java.awt.Color(222,222,222));
            Res.setBackground(new java.awt.Color(222,222,222));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel2.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(237,237,237));
            jLabel3.setForeground(new java.awt.Color(237,237,237));
            jLabel11.setForeground(new java.awt.Color(237,237,237));
            Adder.setForeground(new java.awt.Color(237,237,237));
            Adder.setBackground(new java.awt.Color(7,131,216));
            Name1.setForeground(Color.white);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel3.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(237,237,237));
            FilterWords.setForeground(new java.awt.Color(237,237,237));
            update.setForeground(new java.awt.Color(237,237,237));
            jLabel10.setForeground(new java.awt.Color(237,237,237));
            jLabel9.setForeground(new java.awt.Color(237,237,237));
            jLabel8.setForeground(new java.awt.Color(237,237,237));
            jLabel7.setForeground(new java.awt.Color(237,237,237));
            Delete.setForeground(new java.awt.Color(237,237,237));
            Delete.setBackground(new java.awt.Color(7,131,216));
            Edit.setForeground(new java.awt.Color(237,237,237));
            Edit.setBackground(new java.awt.Color(7,131,216));
            jButton3.setForeground(new java.awt.Color(237,237,237));
            jButton3.setBackground(new java.awt.Color(7,131,216));
            charFilter.setBackground(new java.awt.Color(222,222,222));
            Name2.setForeground(Color.white);
            jList1.setBackground(new java.awt.Color(178,194,201));
            jList2.setBackground(new java.awt.Color(178,194,201));
        }
        else
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel1.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(51, 51, 51));
            jLabel6.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setBackground(new java.awt.Color(51,168,249));
            ArEng.setForeground(new java.awt.Color(51, 51, 51));
            ArEng.setBackground(new java.awt.Color(51,168,249));
            Name.setForeground(Color.black);
            ArabKey.setBackground(new java.awt.Color(235,235,235));
            EnglishKey.setBackground(new java.awt.Color(235,235,235));
            Res.setBackground(new java.awt.Color(235,235,235));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel2.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(51, 51, 51));
            jLabel3.setForeground(new java.awt.Color(51, 51, 51));
            jLabel11.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setBackground(new java.awt.Color(51,168,249));
            Name1.setForeground(Color.black);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel3.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(51, 51, 51));
            FilterWords.setForeground(new java.awt.Color(51, 51, 51));
            update.setForeground(new java.awt.Color(51, 51, 51));
            jLabel10.setForeground(new java.awt.Color(51, 51, 51));
            jLabel9.setForeground(new java.awt.Color(51, 51, 51));
            jLabel8.setForeground(new java.awt.Color(51, 51, 51));
            jLabel7.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setBackground(new java.awt.Color(51,168,249));
            Edit.setForeground(new java.awt.Color(51, 51, 51));
            Edit.setBackground(new java.awt.Color(51,168,249));
            jButton3.setForeground(new java.awt.Color(51, 51, 51));
            jButton3.setBackground(new java.awt.Color(51,168,249));
            charFilter.setBackground(new java.awt.Color(235,235,235));
            Name2.setForeground(Color.black);
            jList1.setBackground(new java.awt.Color(207,232,243));
            jList2.setBackground(new java.awt.Color(207,232,243));
        }
    }//GEN-LAST:event_DarkMode1ActionPerformed

    private void DarkMode2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarkMode2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DarkMode2MouseEntered

    private void DarkMode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkMode2ActionPerformed
        if(accounts.dark == false)
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel1.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(237,237,237));
            jLabel6.setForeground(new java.awt.Color(237,237,237));
            jLabel2.setForeground(new java.awt.Color(237,237,237));
            EngAr.setForeground(new java.awt.Color(237,237,237));
            EngAr.setBackground(new java.awt.Color(7,131,216));
            ArEng.setForeground(new java.awt.Color(237,237,237));
            ArEng.setBackground(new java.awt.Color(7,131,216));
            Name.setForeground(Color.white);
            ArabKey.setBackground(new java.awt.Color(222,222,222));
            EnglishKey.setBackground(new java.awt.Color(222,222,222));
            Res.setBackground(new java.awt.Color(222,222,222));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel2.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(237,237,237));
            jLabel3.setForeground(new java.awt.Color(237,237,237));
            jLabel11.setForeground(new java.awt.Color(237,237,237));
            Adder.setForeground(new java.awt.Color(237,237,237));
            Adder.setBackground(new java.awt.Color(7,131,216));
            Name1.setForeground(Color.white);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(0,102,102));
            kGradientPanel3.setkEndColor(new java.awt.Color(0,51,51));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(237,237,237));
            FilterWords.setForeground(new java.awt.Color(237,237,237));
            update.setForeground(new java.awt.Color(237,237,237));
            jLabel10.setForeground(new java.awt.Color(237,237,237));
            jLabel9.setForeground(new java.awt.Color(237,237,237));
            jLabel8.setForeground(new java.awt.Color(237,237,237));
            jLabel7.setForeground(new java.awt.Color(237,237,237));
            Delete.setForeground(new java.awt.Color(237,237,237));
            Delete.setBackground(new java.awt.Color(7,131,216));
            Edit.setForeground(new java.awt.Color(237,237,237));
            Edit.setBackground(new java.awt.Color(7,131,216));
            jButton3.setForeground(new java.awt.Color(237,237,237));
            jButton3.setBackground(new java.awt.Color(7,131,216));
            charFilter.setBackground(new java.awt.Color(222,222,222));
            Name2.setForeground(Color.white);
            jList1.setBackground(new java.awt.Color(178,194,201));
            jList2.setBackground(new java.awt.Color(178,194,201));
        }
        else
        {
                                // Tab 1
            kGradientPanel1.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel1.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel1.repaint();
            accounts.dark = !accounts.dark;
            jLabel5.setForeground(new java.awt.Color(51, 51, 51));
            jLabel6.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setForeground(new java.awt.Color(51, 51, 51));
            EngAr.setBackground(new java.awt.Color(51,168,249));
            ArEng.setForeground(new java.awt.Color(51, 51, 51));
            ArEng.setBackground(new java.awt.Color(51,168,249));
            Name.setForeground(Color.black);
            ArabKey.setBackground(new java.awt.Color(235,235,235));
            EnglishKey.setBackground(new java.awt.Color(235,235,235));
            Res.setBackground(new java.awt.Color(235,235,235));
            
                                // Tab 2
            kGradientPanel2.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel2.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel2.repaint();
            jLabel1.setForeground(new java.awt.Color(51, 51, 51));
            jLabel3.setForeground(new java.awt.Color(51, 51, 51));
            jLabel11.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setForeground(new java.awt.Color(51, 51, 51));
            Adder.setBackground(new java.awt.Color(51,168,249));
            Name1.setForeground(Color.black);
            
                                // Tab 3
            kGradientPanel3.setkStartColor(new java.awt.Color(51,153,255));
            kGradientPanel3.setkEndColor(new java.awt.Color(153,204,255));
            kGradientPanel3.repaint();
            jLabel4.setForeground(new java.awt.Color(51, 51, 51));
            FilterWords.setForeground(new java.awt.Color(51, 51, 51));
            update.setForeground(new java.awt.Color(51, 51, 51));
            jLabel10.setForeground(new java.awt.Color(51, 51, 51));
            jLabel9.setForeground(new java.awt.Color(51, 51, 51));
            jLabel8.setForeground(new java.awt.Color(51, 51, 51));
            jLabel7.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setForeground(new java.awt.Color(51, 51, 51));
            Delete.setBackground(new java.awt.Color(51,168,249));
            Edit.setForeground(new java.awt.Color(51, 51, 51));
            Edit.setBackground(new java.awt.Color(51,168,249));
            jButton3.setForeground(new java.awt.Color(51, 51, 51));
            jButton3.setBackground(new java.awt.Color(51,168,249));
            charFilter.setBackground(new java.awt.Color(235,235,235));
            Name2.setForeground(Color.black);
            jList1.setBackground(new java.awt.Color(207,232,243));
            jList2.setBackground(new java.awt.Color(207,232,243));
        }
    }//GEN-LAST:event_DarkMode2ActionPerformed

    

    private void updateList()
    {
        model.clear();
            for (int i = 3 ; i < srch.getEntriesLength() ; i++){
                String asem = srch.getEntries()[i];
                System.out.println(asem);
                model.add(i-3,asem );
            }
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddAr;
    private javax.swing.JTextField AddEng;
    private javax.swing.JButton Adder;
    private javax.swing.JButton ArEng;
    private javax.swing.JTextField ArabKey;
    private java.awt.Button DarkMode;
    private java.awt.Button DarkMode1;
    private java.awt.Button DarkMode2;
    private javax.swing.JButton Delete;
    private javax.swing.ButtonGroup DeleteMode;
    private javax.swing.JButton Edit;
    private javax.swing.JButton EngAr;
    private javax.swing.JTextField EnglishKey;
    private javax.swing.JLabel FilterWords;
    private javax.swing.JRadioButton Multiple;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JTextField Res;
    private javax.swing.JRadioButton Single;
    private javax.swing.JTextField charFilter;
    private javax.swing.JButton jButton3;
    private java.awt.Button jEdit;
    private java.awt.Button jEdit1;
    private java.awt.Button jEdit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private java.awt.Button jLogout;
    private java.awt.Button jLogout1;
    private java.awt.Button jLogout2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
